### ISSUE TITLE
在首頁新增「Surelife 輕鬆找保險」的 logo 和連結

### ISSUE THREAD

**Issue by gundamew** [smstw/SMS-Official-Site#21]
圖片放在 NAS 的 sms_taiwan/dropbox/sms_share/Logo/Surelife logo/surelife-logo-300x300.jpg

**Comment by gundamew** [comment]
本 issue 的修改如下列：

- ec12ef79a02d12dfe54c3afa55ed222614fb5363
- c512efdb331926233b8cd903fe07e49f0b25bd6c

**Comment by LeoOnTheEarth** [comment]
已完成，close issue
