### ISSUE TITLE
在首頁新增工程師 Steven 的頭像

### ISSUE THREAD

**Issue by gundamew** [smstw/SMS-Official-Site#22]
可以跟 #21 一起進行

**Comment by gundamew** [comment]
本 issue 的相關修改如下列：

- f4a6ed2cd868022ab60027576b010e7afb10b4e8
- b1fac0fc529cd8b839073664a8d5a82c000cb3ec
- 8290ebe4ddcb034321e9e702a82cb7edf9209cce
- 2c95412a4b218b69562bf013c3351788171488ee

**Comment by bblurock** [comment]
@michael520 這也麻煩你更新一下正式機

**Comment by michael520** [comment]
已更新完成

**Comment by asika32764** [comment]
![p-2015-03-27-1_032715_105802_pm](https://cloud.githubusercontent.com/assets/1639206/6870113/c4428386-d4d4-11e4-8aae-8744178fb909.jpg)

眼睛要對齊

**Comment by gundamew** [comment]
？！ :frowning:

**Comment by LeoOnTheEarth** [comment]
已完成，close issue
